# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI with Ant

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Set up Ant
      run: |
        sudo apt-get update
        sudo apt-get install -y ant

    - name: List directory contents for debugging
      run: |
        pwd
        ls -la
        find . -name "build.xml"

    - name: Create lib directory
      run: |
        cd "TUBES_PBO_Kelompok 9"
        mkdir -p lib

    - name: Download JUnit
      run: |
        cd "TUBES_PBO_Kelompok 9"
        wget https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar -P lib/
        wget https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar -P lib/

    - name: Grant execute permission for build scripts
      run: |
        cd "TUBES_PBO_Kelompok 9"
        chmod +x build.xml
        find nbproject -name "*.xml" -exec chmod +x {} \;

    - name: Build with Ant
      run: |
        cd "TUBES_PBO_Kelompok 9"
        ant -noinput -f build.xml clean jar

    - name: Run Tests
      run: |
        cd "TUBES_PBO_Kelompok 9"
        ant test
